config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/error_404'
  get 'errors/error_505'
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  delete 'logout' => 'session#destroy'
  get '/auth/:provider/callback' => 'session#create'
  resources :users
  resources :posts do
    resources :comments
    resource :likes
  end
  resource :comments do
    resource :comments
  end

  match '*not_found' => 'errors#error_404', via: :all
end

app/views/shared/_comment_form.html.erb
<%= form_for :comment, url: post_comments_path(post) do |f| %>
  <div class="field">
    <%= f.text_area :body, placeholder: "...new comment..." %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/_current_user.html.erb
<li>
  <img src=<%= @current_user.image_url %> alt="User" />
  <%= link_to @current_user.first_name, user %>
</li>

app/views/shared/_dropdown.html.erb
<div class="dropdown">
  <button class="dropbtn">More</button>
  <div class="dropdown-content">
    <div class="delete_post">
      <%= link_to "Delete photo", post, method: :delete,
                  data: { confirm: "You sure?" } %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_likes.html.erb
<% if logged? %>
  <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  <%= button_to 'Like', post_likes_path(post), method: :post %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for :post, url: posts_path, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.text_area :title, placeholder: "...photo title..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="photo">
    <%= f.file_field :photo, accept: 'image/jpg,image/gif,image/png,image/jpeg' %>
  </span>
<% end %>

<script type="text/javascript">
    $('#post_photo').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_sort.html.erb
  <div class="dropdown">
    <button class="dropbtn">Sort</button>
    <div class="dropdown-content">
      <%= link_to 'Date ▼', posts_path(sorting: 'created_at ASC') %>
      <%= link_to 'Date ▲', posts_path(sorting: 'created_at DESC') %>
    </div>
  </div>