config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/error_404'
  get 'errors/error_505'
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  delete 'logout' => 'session#destroy'
  get '/auth/:provider/callback' => 'session#create'
  resources :users
  resources :posts do
    resources :comments
    resource :likes
  end
  resource :comments do
    resource :comments
  end

  match '*not_found' => 'errors#error_404', via: :all
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made by: <a href="https://vk.com/deaddiamon"> Dmitry Bayandin</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "PhotoContest", root_path, id: "logo" %>
    <nav>
      <% if logged? %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.admin? %>
        <% end %>
        <li><%= link_to "My profile", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <li><%= link_to "Users", users_path %> </li>
        <li><%= link_to "All posts", posts_path %></li>
      </ul>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'custom', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/errors' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>